#!/usr/bin/env bash
set -euo pipefail
root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
export GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null
export GIT_AUTHOR_NAME='Release Test' GIT_AUTHOR_EMAIL='release@example.invalid'
export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
export CARGO_NET_OFFLINE=true
count=0
pass() { count=$((count + 1)); printf 'ok %s - %s\n' "$count" "$*"; }
fail() { printf 'not ok - %s\n' "$*" >&2; exit 1; }
expect_failure() {
    if "$@" >"$tmp/output" 2>&1; then fail "unexpected success: $*"; fi
}
parse() { awk -v mode="$1" -v version="${2:-}" -v date=2026-10-02 -f "$root/scripts/changelog.awk" "$tmp/CHANGELOG.md"; }
level() {
    printf '# Changelog\n\n## [Unreleased]\n\n### %s\n\n%s\n' "$1" "$2" >"$tmp/CHANGELOG.md"
    [[ $(parse level) == "$3" ]] || fail "$1 bump"
    pass "$1 bump"
}
level 'Breaking changes' 'Migration instructions.' 3
level Added 'A new feature.' 2
level Changed 'A new default.' 2
level Fixed 'A bug fix.' 1
level Security 'A vulnerability fix.' 1
level Documentation 'An upgrade guide.' 1
cat >>"$tmp/CHANGELOG.md" <<'DOC'

### Added

Feature.

### Breaking changes

Migration.
DOC
[[ $(parse level) == 3 ]] || fail precedence
pass 'highest section wins'
for body in '' '### Fixed' $'### Upgrade notes\n\nInstructions only.' $'### Typo\n\nChange.' $'### Fixed\nFix\n### Fixed\nDuplicate' $'### Fixed\n```sh\nunterminated' $'### Fixed\n<!-- unfinished' $'### Fixed\n<!-- placeholder -->' 'Ungrouped prose'; do
    printf '## [Unreleased]\n\n%s\n' "$body" >"$tmp/CHANGELOG.md"
    expect_failure parse level
done
pass 'empty, unknown, duplicate, malformed and advisory-only sections rejected'
printf '## [Unreleased]\n### Fixed\nFix\n## [Unreleased]\n### Added\nFeature\n' >"$tmp/CHANGELOG.md"
expect_failure parse level
pass 'duplicate Unreleased rejected'
cat >"$tmp/CHANGELOG.md" <<'DOC'
# Changelog

## [Unreleased]

### Breaking changes

<!--
### Unknown heading inside a comment
not a change
-->

### Fixed

Fix for {{version}} on {{date}}.

#### Example

````markdown
### Breaking changes
## [Unreleased]
```
````

~~~yaml
### Not a heading either
~~~

## [0.1.0] - 2026-01-01

### Fixed

Historical {{version}} and {{date}} remain literal.
DOC
[[ $(parse level) == 1 ]] || fail 'fenced headings or comments affected inference'
pass 'nested headings, comments, and variable-length fences'
sed -n '/^## \[0.1.0\]/,$p' "$tmp/CHANGELOG.md" >"$tmp/history"
parse stamp 0.1.1 >"$tmp/stamped"
grep -Fq 'Fix for 0.1.1 on 2026-10-02.' "$tmp/stamped" || fail placeholders
sed -n '/^## \[0.1.0\]/,$p' "$tmp/stamped" >"$tmp/history-after"
cmp "$tmp/history" "$tmp/history-after" || fail 'historical text changed'
mv "$tmp/stamped" "$tmp/CHANGELOG.md"
expect_failure parse level
parse notes 0.1.1 >"$tmp/notes"
grep -Fq 'Fix for 0.1.1' "$tmp/notes" || fail notes
if grep -Fq Historical "$tmp/notes"; then fail 'notes include other releases'; fi
expect_failure parse notes 9.9.9
pass 'stamp, scoped placeholders, fresh skeleton, history preservation, notes extraction'

fixture_count=0
fixture() {
    fixture_count=$((fixture_count + 1))
    repo="$tmp/repo-$fixture_count"
    remote="$tmp/remote-$fixture_count.git"
    git init -q --bare --initial-branch=master "$remote"
    git init -q -b master "$repo"
    mkdir -p "$repo/scripts" "$repo/src"
    cp "$root/scripts/release" "$root/scripts/changelog.awk" "$repo/scripts/"
    cp "$root/release.toml" "$repo/"
    cat >"$repo/Cargo.toml" <<'TOML'
[package]
name = "fransson"
version = "0.1.0"
edition = "2021"
description = "Release test fixture"
license = "Apache-2.0"
repository = "https://example.invalid/fransson"
TOML
    cat >"$repo/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "fransson"
version = "0.1.0"
LOCK
    printf 'fn main() {}\n' >"$repo/src/main.rs"
    printf '/target\n' >"$repo/.gitignore"
    printf '# Changelog\n\n## [Unreleased]\n\n### Fixed\n\nFix for {{version}}.\n' >"$repo/CHANGELOG.md"
    git -C "$repo" add .
    git -C "$repo" commit -qm 'fix: fixture'
    git -C "$repo" remote add origin "$remote"
    git -C "$repo" push -qu origin master
}
commit_fixture() {
    git -C "$repo" add .
    git -C "$repo" commit -qm 'test: update fixture'
    git -C "$repo" push -q origin master
}
reject_branch_push() {
    cat >"$remote/hooks/update" <<'HOOK'
#!/usr/bin/env bash
[[ $1 != refs/heads/master ]]
HOOK
    chmod +x "$remote/hooks/update"
}
run_release() { "$repo/scripts/release" "$@"; }
fixture
before=$(git -C "$repo" rev-parse HEAD)
run_release >"$tmp/output"
grep -Fq '0.1.0 → 0.1.1' "$tmp/output" || fail 'patch inference'
[[ -z $(git -C "$repo" status --porcelain) && $(git -C "$repo" rev-parse HEAD) == "$before" ]] || fail 'preview mutated repository'
run_release --version 1.0.0 >"$tmp/output"
grep -Fq '0.1.0 → 1.0.0' "$tmp/output" || fail 'explicit 1.0'
for version in '' 0.0.9 0.1.0 01.2.3 1.0.0-rc.1 nope 999999999999999999.0.0; do expect_failure run_release --version "$version"; done
expect_failure run_release --version
expect_failure run_release --wat
pass 'read-only preview and explicit stable-version validation'
sed -i 's/### Fixed/### Breaking changes/' "$repo/CHANGELOG.md"
run_release >"$tmp/output"
grep -Fq '0.1.0 → 0.2.0' "$tmp/output" || fail '0.x breaking policy'
sed -i 's/version = "0.1.0"/version = "1.2.3"/' "$repo/Cargo.toml"
run_release >"$tmp/output"
grep -Fq '1.2.3 → 2.0.0' "$tmp/output" || fail 'stable breaking policy'
pass '0.x and stable breaking policies'
expect_failure run_release --execute
grep -Fq 'must be clean' "$tmp/output" || fail 'dirty tree guard'
pass 'dirty tracked files rejected'
fixture
touch "$repo/untracked"
expect_failure run_release --execute
rm "$repo/untracked"
git -C "$repo" checkout -qb feature
expect_failure run_release --execute
grep -Fq 'must run on master' "$tmp/output" || fail 'branch guard'
git -C "$repo" checkout -q master
git -C "$repo" branch --unset-upstream
expect_failure run_release --execute
git -C "$repo" branch -qu origin/master
pass 'untracked files, wrong branch and missing upstream rejected'
printf 'local work\n' >"$repo/new-file"
git -C "$repo" add . && git -C "$repo" commit -qm 'docs: local work'
expect_failure run_release --execute
grep -Fq 'must match origin/master' "$tmp/output" || fail 'local ahead guard'
git -C "$repo" push -q origin master
git clone -q "$remote" "$tmp/peer"
printf 'remote work\n' >"$tmp/peer/remote-file"
git -C "$tmp/peer" add . && git -C "$tmp/peer" commit -qm 'docs: remote work'
git -C "$tmp/peer" push -q origin master
expect_failure run_release --execute
grep -Fq 'must match origin/master' "$tmp/output" || fail 'remote ahead guard'
pass 'local and remote divergence rejected'
fixture
git -C "$repo" tag fransson-v0.1.1
expect_failure run_release --execute
grep -Fq 'already exists' "$tmp/output" || fail 'duplicate local tag guard'
git -C "$repo" push -q origin refs/tags/fransson-v0.1.1
git -C "$repo" tag -d fransson-v0.1.1 >/dev/null
expect_failure run_release --execute
grep -Fq 'already exists' "$tmp/output" || fail 'duplicate remote tag guard'
pass 'existing local and remote tags rejected'

# Stub only cargo-release mechanics; exercise the real wrapper, hook and Git.
mkdir "$tmp/bin"
printf '#!/usr/bin/env bash\nexit 0\n' >"$tmp/bin/cargo-release"
cat >"$tmp/bin/cargo" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
[[ $1 == release ]]
step=$2
shift 2
if [[ $step == version ]]; then version=$1; shift; else
    version=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
fi
[[ $1 == --isolated && $2 == --config && $4 == --execute && $5 == --no-confirm ]]
case "$step" in
    version) sed -i "s/version = \"0.1.0\"/version = \"$version\"/" Cargo.toml Cargo.lock ;;
    hook)
        if [[ ${FAKE_HOOK_FAIL:-false} == true ]]; then version=9.9.9; fi
        DRY_RUN=false NEW_VERSION=$version bash scripts/release --stamp ;;
    commit)
        git add Cargo.toml Cargo.lock CHANGELOG.md
        git commit -qm "chore: release $version" ;;
    tag) git tag -a "fransson-v$version" -m "chore: release $version" ;;
    push) git push --atomic origin HEAD:refs/heads/master "refs/tags/fransson-v$version" ;;
    *) exit 1 ;;
esac
STUB
chmod +x "$tmp/bin/"*
original_path=$PATH
export PATH="$tmp/bin:$PATH"
fixture
run_release --execute >"$tmp/output" 2>&1 || { cat "$tmp/output"; fail 'stubbed release'; }
[[ -z $(git -C "$repo" status --porcelain) ]] || fail 'release not clean'
[[ $(git --git-dir="$remote" rev-parse master) == "$(git -C "$repo" rev-parse HEAD)" ]] || fail 'branch not pushed'
[[ $(git --git-dir="$remote" rev-parse 'fransson-v0.1.1^{commit}') == "$(git -C "$repo" rev-parse HEAD)" ]] || fail 'tag not pushed'
run_release --verify-tag fransson-v0.1.1
expect_failure run_release --verify-tag fransson-v0.1.2
expect_failure run_release --verify-tag invalid
expect_failure run_release --execute
pass 'full wrapper lifecycle, CI validation and safe repeat rejection'
fixture
before=$(git -C "$repo" rev-parse HEAD)
cp "$repo/CHANGELOG.md" "$tmp/before-hook"
export FAKE_HOOK_FAIL=true
expect_failure run_release --execute
unset FAKE_HOOK_FAIL
cmp "$repo/CHANGELOG.md" "$tmp/before-hook" || fail 'failed hook changed changelog'
[[ $(git -C "$repo" rev-parse HEAD) == "$before" && -z $(git -C "$repo" tag --list) ]] || fail 'failed hook committed or tagged'
pass 'failed hook leaves no commit or tag'
fixture
before=$(git --git-dir="$remote" rev-parse master)
reject_branch_push
expect_failure run_release --execute
grep -Fq 'Release stopped' "$tmp/output" || fail 'missing recovery message'
[[ $(git --git-dir="$remote" rev-parse master) == "$before" && -z $(git --git-dir="$remote" tag --list) ]] || fail 'failed atomic push updated remote'
local_tag=$(git -C "$repo" rev-parse fransson-v0.1.1)
rm "$remote/hooks/update"
run_release --verify-tag fransson-v0.1.1
git -C "$repo" push --atomic -q origin HEAD:refs/heads/master refs/tags/fransson-v0.1.1
[[ $(git --git-dir="$remote" rev-parse fransson-v0.1.1) == "$local_tag" ]] || fail 'recovery moved tag'
pass 'failed push and recovery preserve tag identity'
export PATH=$original_path

if [[ ${RELEASE_TEST_REAL:-0} == 1 ]]; then
    command -v cargo-release >/dev/null || fail 'real integration requires cargo-release'
    fixture
    run_release --execute >"$tmp/output" 2>&1 || { cat "$tmp/output"; fail 'real cargo-release integration'; }
    run_release --verify-tag fransson-v0.1.1
    [[ -z $(git -C "$repo" status --porcelain) ]] || fail 'real release not clean'
    [[ $(git --git-dir="$remote" rev-parse 'fransson-v0.1.1^{commit}') == "$(git -C "$repo" rev-parse HEAD)" ]] || fail 'real tag not pushed'
    [[ $(git -C "$repo" cat-file -t fransson-v0.1.1) == tag ]] || fail 'real tag not annotated'
    grep -Fq 'version = "0.1.1"' "$repo/Cargo.lock" || fail 'lockfile not updated'
    pass 'real cargo-release commit, hook, lockfile, annotated tag and atomic push'

    fixture
    sed -i 's/^pre-release-hook = .*/pre-release-hook = ["false"]/' "$repo/release.toml"
    commit_fixture
    before=$(git -C "$repo" rev-parse HEAD)
    cp "$repo/CHANGELOG.md" "$tmp/before-real-hook"
    expect_failure run_release --execute
    grep -Fq 'stopped during hook' "$tmp/output" || { cat "$tmp/output"; fail 'real hook failure'; }
    cmp "$repo/CHANGELOG.md" "$tmp/before-real-hook" || fail 'real failed hook changed notes'
    [[ $(git -C "$repo" rev-parse HEAD) == "$before" && -z $(git -C "$repo" tag --list) ]] || fail 'real hook failure committed or tagged'
    pass 'real cargo-release stops before commit when hook fails'

    fixture
    before=$(git --git-dir="$remote" rev-parse master)
    reject_branch_push
    expect_failure run_release --execute
    grep -Fq 'stopped during push' "$tmp/output" || { cat "$tmp/output"; fail 'real push failure'; }
    [[ $(git --git-dir="$remote" rev-parse master) == "$before" && -z $(git --git-dir="$remote" tag --list) ]] || fail 'real push was not atomic'
    local_tag=$(git -C "$repo" rev-parse fransson-v0.1.1)
    rm "$remote/hooks/update"
    run_release --verify-tag fransson-v0.1.1
    git -C "$repo" push --atomic -q origin HEAD:refs/heads/master refs/tags/fransson-v0.1.1
    [[ $(git --git-dir="$remote" rev-parse fransson-v0.1.1) == "$local_tag" ]] || fail 'real recovery moved tag'
    pass 'real atomic push failure and recovery preserve tag identity'
fi
printf '\n%s release-tooling checks passed.\n' "$count"
